### ISSUE TITLE
Then chaining broken when returning `Any`

### ISSUE THREAD

**Issue by mojidabckuu** [mxcl/PromiseKit#586] opened 2016-11-09 12:18 UTC
* PromiseKit version: 4
* Xcode version: 8.1(8B62)
* CocoaPods version: 1.0.1

I am trying to understand the concept. I had expectation that when I chain the promises then it will execute subsequently 
```swift
let _ = firstly { () -> Promise<Any> in
            return Promise(resolvers: { (fulfill, reject) in
                DispatchQueue.global().asyncAfter(deadline: .now() + .seconds(2), execute: {
                    print("FULLFIL 1")
                    fulfill(1)
                })
            })
            }.then { (any) -> Promise<Any> in
                return Promise(resolvers: { (fulfill, reject) in
                    DispatchQueue.global().asyncAfter(deadline: .now() + .seconds(5), execute: {
                        print("FULLFIL 2")
                        fulfill(2)
                    })
                })
            }.then { (any) -> Promise<Any> in
                return Promise(resolvers: { (fulfill, reject) in
                    DispatchQueue.global().asyncAfter(deadline: .now() + .seconds(1), execute: {
                        print("FULLFIL 3")
                        fulfill(3)
                    })
                })
            }.then { (any) -> Any in
                print("HERE IS A NUMBER \(any.value)")
                return any
        }
```
Produces next output:
```
FULLFIL 1
HERE IS A NUMBER nil
FULLFIL 3
FULLFIL 2
```
Actually the plain is to make 4 API calls. 
Am I doing something wrong?

**Comment by zlangley** [comment] 2016-11-09 12:35
The problem is your `then` methods are being inferred to use the signature `then(execute: (Promise<Any>) -> Any)` instead of `then(execute: (Any) -> Any)` since `Promise<Any>` conforms to `Any`. Either explicitly annotate your parameter as `Any` or use a more concrete type, like `Promise<Int>` in this case.

```swift
_ = firstly { () -> Promise<Any> in
    return …
}.then { (any: Any) -> Promise<Any> in
    return …
}.then { (any: Any) -> Promise<Any> in
    return …
}.then { (any: Any) -> Any in
    print("HERE IS A NUMBER \(any)")
    return any
}
```

or

```swift
_ = firstly { () -> Promise<Int> in
    return …
}.then { value -> Promise<Int> in
    return …
}.then { value -> Promise<Int> in
    return …
}.then { value -> Int in
    print("HERE IS A NUMBER \(value)")
    return value
}
```

**Comment by zlangley** [comment] 2016-11-09 12:44
To illustrate what's going on more concretely:

```
let foo = firstly { () -> Promise<Any> in
    return Promise(value: 1)
}.then { value in
    // `value` is inferred to be `Promise<Any>` (surprisingly)
    return value
}

foo.then { value in
    // `value` is inferred to be `Any` (expected)
    return value
}

_ = firstly { () -> Promise<Int> in
    return Promise(value: 1)
}.then { value in
    // `value` is inferred to be `Int` (expected)
    return value
}
```

**Comment by mojidabckuu** [comment] 2016-11-09 13:15
@zlangley Thank you for the response. I understood the problem. But why Swift thinks that `Promise<Any>` it matches with `Any`?

**Comment by mxcl** [comment] 2016-11-09 16:46
Swift bug, it is interpreting `Promise<Any>` as `Optional<T>`  rather than `Promise<Any>` and thus choosing the wrong version of `then` causing it not to wait on the promise.

As a workaround, don't use `Any`, this should be reported against Swift. I'm not sure there is anything we can do to fix it.

**Comment by mxcl** [comment] 2016-11-09 16:48
Changing them to `Int` fixes it:

![screen shot 2016-11-09 at 11 48 04 am](https://cloud.githubusercontent.com/assets/58962/20146572/70b5745a-a672-11e6-91ac-682b8ce5d285.png)

**Comment by mxcl** [comment] 2016-11-09 16:51
Perhaps we should add a `fatalError`:

```swift
guard !(promise.value is Promise) else { fatalError() }
```

So in future we can catch this better? I'm usually not a fan of this sort of thing, but since the behavior is otherwise broken, it seems fair.

**Comment by mxcl** [comment] 2016-11-09 16:53
Sorry I see @zlangley already identified this, I only scanned over the responses… my bad.

**Comment by mojidabckuu** [comment] 2016-11-09 17:09
@mxcl that's true. I made a POC for that case. And pattern matching for functions works unexpectedly. So in my case as workaround I made an extension for `Promise` called `else` instead of `then` to support the case with `Promise<Any>` once Swift team fix it.

**Comment by banxi1988** [comment] 2016-11-26 08:51
Maybe  one of two different `then` method should change its name to a new one.

**Comment by mxcl** [comment] 2017-01-30 22:05
The suggested fix for anyone coming here is to not use `Promise<Any>`.

**Comment by mxcl** [comment] 2017-11-05 22:23
Fixed by PromiseKit 5 being more strict with `then`.

**Closed by mxcl** 2017-11-05 22:23 UTC
Labels: bug, swift
