### ISSUE TITLE
promiseWithBooleanAdapterBlock

### ISSUE THREAD

**Issue by yunjinghui123** [mxcl/PromiseKit#1325] opened 2023-09-22 07:19 UTC
![image](https://github.com/mxcl/PromiseKit/assets/9649401/e9aea2e9-6ad0-4ff4-89db-bbc4dca79c90)

promiseWithBooleanAdapterBlock adapter(YES) ,but then value is NO, why?

Xcode15

PromiseKit8.1.1

**Comment by RomanPodymov** [comment] 2023-09-22 13:33
Hello @yunjinghui123 
In your example `v` is not `BOOL`, it's `id`. Just change argument type in your example.

**Comment by yunjinghui123** [comment] 2023-09-25 07:14
> Hello @yunjinghui123
> In your example `v` is not `BOOL`, it's `id`. Just change argument type in your example.

Thank you

**Comment by mxcl** [comment] 2023-09-27 19:03
it's a bug based on our docs. I don't remember this function, did you add it @RomanPodymov ?

**Comment by RomanPodymov** [comment] 2023-09-28 07:10
> it's a bug based on our docs. I don't remember this function, did you add it @RomanPodymov ?

Hello @mxcl
I also don't remember this function, but I think I explained @yunjinghui123 what is wrong. @yunjinghui123 can we close the issue?

**Comment by mxcl** [comment] 2023-09-28 11:03
I guess I added it years ago for some reason.

It should work like the other `then()` and automatically convert from `id` to `BOOL` based on the provided args, but at this point I think we can all agree this “bug” is working as intended.

**Closed by mxcl** 2023-09-28 11:03 UTC
Labels: bug

**Comment by RomanPodymov** [comment] 2023-10-01 08:18
Hello @mxcl
As I can see `promiseWithBooleanAdapterBlock` uses `[NSNumber numberWithBool:]` because `AnyPromise` uses `id` for `value`.

**Comment by RomanPodymov** [comment] 2023-10-01 08:22
@yunjinghui123 So you can use `NSNumber` in your example
```
void (^fetch)(PMKBooleanAdapter) = ^(PMKBooleanAdapter block){
    block(YES, nil);
};
[AnyPromise promiseWithBooleanAdapterBlock:fetch].then(^(NSNumber* obj){
    XCTAssertEqualObjects(obj, @YES);
});
```

**Comment by yunjinghui123** [comment] 2023-11-03 07:09
> fetch

I will use it this way.Thank you！
