### ISSUE TITLE
AnyPromise doesn't support non-object types

### ISSUE THREAD

**Issue by b123400** [mxcl/PromiseKit#357] opened 2016-02-03 10:24 UTC
In the [tutorial](http://promisekit.org/language-bridging), it says:

```
class Foo {
    func bar1() -> Promise<String> {
        //…
    }

    @objc func bar2() -> AnyPromise {

        // since ObjC cannot see generic objects we have
        // to bridge by writing an adapting function.

        return AnyPromise(bound: bar1())
    }
}
```

This doesn't work because Swift's `String` is a value type, and AnyPromise only accepts `AnyObject`, not `Any`. Is this intentional? Should I change it to `Any`?

Related: #200 (Swift array is value type, not object)

**Comment by mxcl** [comment] 2016-02-04 04:54
`String` is bridged to `NSString` in such situations and NSString is an object.

**Comment by mxcl** [comment] 2016-02-04 05:03
> Should I change it to Any?

`AnyPromise` is for ObjectiveC (mostly), really it should be called `AnyObjectPromise` but that was unwieldy.

**Comment by b123400** [comment] 2016-02-04 08:56
I thought it will be bridged to `NSString` as well, but it doesn't.

![original_account itunes swift 2016-02-03 17-24-53](https://cloud.githubusercontent.com/assets/127193/12810243/e390fbd2-cb5f-11e5-8f7b-d7382126b03e.png)

The functional signature `init<T: AnyObject>` means that `T` has to be an `AnyObject` but `String` is not.
May I ask where does the bridging happen?

**Comment by afladmark** [comment] 2016-02-06 17:16
I get the same compilation error with Promise<Bool>.

**Comment by nathanhosselton** [comment] 2016-02-10 19:56
@b123400 Swift should be performing the bridging [automatically](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/WorkingWithCocoaDataTypes.html#//apple_ref/doc/uid/TP40014216-CH6-XID_43). I am unsure why this isn't happening.

I've included new convenience inits in #359 as a workaround. @mxcl If you think this is the way to go I will merge.

**Comment by b123400** [comment] 2016-02-15 13:55
I think I know why is it not getting bridged.
Seems that Swift only bridge types when it is not a member of a generic. 

```
func foo<T:AnyObject>(input:T) {}
foo("a") // no problem

func baz <T:AnyObject>(input:Optional<T>) {}
let b:Optional<String> = .Some("b")
baz(b) // error: Cannot convert value of type 'Optional<String>' to expected argument type 'Optional<...>`
```

Not sure if this is an expected behaviour or not.

**Comment by nathanhosselton** [comment] 2016-02-29 00:20
@b123400 I did some testing with your code as well and I agree that your examples seem to pinpoint the source of the bridging failure, although to be a bit more specific it seems to only fail when the parameter is both generic AND optional. The closest reference I could find to this issue is [this SO question](http://stackoverflow.com/questions/32080420/casting-to-generic-optional-in-swift) whose answer indicates that the issue is really to do with not being able to cast optionals to AnyObject or vice versa. This is in line with PK's implementation as well as `AnyPromise`'s default initializer takes a `T?` where T conforms to `AnyObject`, and each of the convenience initializers added to work around the bridging issues for the ObjC types accepts strictly `T`.

If this is the case (and I could be off base) there seems to be three possible courses of action from here:
1) Continue adding convenience inits for these exceptions (simplest resolution though not as nice)
2) Replace `AnyObject` conformance with `Any` in the designated `AnyPromise` init (based on my testing, I think this would work)
3) Remove the optionality of `T` in the designated init.

Unfortunately the latter two would require substantial refactoring in the PromiseKit codebase - the implications for which I have yet to fully research - and as such could potentially demand a 4.0.0 release. I'm also unsure if the reasoning behind making the designated init accept `T?` extends beyond simply allowing users of the library to pass nil (an expected convenience to be sure but perhaps unnecessary?). I suspect not, but I don't know as of now.

Regardless, I think this topic demands some community input.

**Comment by mxcl** [comment] 2016-02-29 19:44
PR looks good.

**Comment by nathanhosselton** [comment] 2016-02-29 20:06
Went ahead and merged the fixes for now but I think the discussion mentioned in my last comment is still warranted. Reopening.

**Comment by b123400** [comment] 2016-02-29 21:40
Suggestion 2) would be the best if it can be implemented, but I wonder if it is possible. Some Swift types cannot be bridged to Objective C (like array of enum), is there way to handle case like this?

**Comment by mxcl** [comment] 2016-07-23 07:10
2) is impossible, Objective-C cannot bridge things that aren't AnyObject.

**Closed by mxcl** 2016-07-23 07:10 UTC
