### ISSUE TITLE
AFNetworking+PromiseKit retain cycle (Swift)

### ISSUE THREAD

**Issue by BarakRL** [mxcl/PromiseKit#281] opened 2015-09-29 16:10 UTC
We have a problem with a retain cycle caused by closures:

```
let (promise, fulfill, reject) = Promise<AnyObject>.pendingPromise()        

let successBlock = { (task: NSURLSessionDataTask!, responseObject: AnyObject!) -> Void in
    fulfill(responseObject)
}

let failureBlock = { (task: NSURLSessionDataTask!, error: NSError!) -> Void in
    reject(error)
}

var dataTask: NSURLSessionDataTask?
switch (httpMethod) {
case .GET:
    dataTask = GET(path, parameters: parameters, success: successBlock, failure: failureBlock)
    break;
case .POST:
    dataTask = POST(path, parameters:parameters, success:successBlock, failure:failureBlock)
    break;
case .PUT:
    dataTask = PUT(path, parameters:parameters, success:successBlock, failure:failureBlock)
    break;
case .DELETE:
    dataTask = DELETE(path, parameters:parameters, success:successBlock, failure:failureBlock)
    break;
}

return promise
```
(all HTTP methods return NSURLSessionDataTask?)

problem is, even if we release the returned promise, the data task captures / holds a reference to the success/failure blocks which in turn holds a reference to the fulfill/reject closures, preventing from the promise from being released.

Any ideas how to avoid this?
Thanks.

**Comment by mxcl** [comment] 2015-09-30 04:49
`fulfill` and `reject` indeed hold a reference to the `Promise` object.

But they release the promise once either `fulfill` or `reject` are called.

What makes you say there is a retain cycle?

**Comment by mxcl** [comment] 2015-10-18 22:34
This is by design, `pendingPromise` splits the ownership of the promise across the three objects. It seems in this case the solution is for the `dataTask` to be released, then it will release its owned objects, which includes its closures, and thus `fulfill` and `reject` will be released.

This would be the correct design considering the intended usage of Swift memory management.

Another solution would be to make `fulfill` and `reject` weak, though feels like “fighting” the system.

**Closed by mxcl** 2015-10-18 22:34 UTC
