### ISSUE TITLE
Can't build 3.0 with carthage

### ISSUE THREAD

**Issue by boberetezeke** [mxcl/PromiseKit#307] opened 2015-10-29 15:53 UTC
When I try to build PromiseKit with Carthage I get (below). I am new to iOS development on this computer and am back to it after a year and a half, so my development setup might not be right. I am not sure what to change to get it working. Also, at least for now, it would be fine just to download a binary build of the 3.0 framework if that's an option.

$ carthage update --platform ios
*** Fetching PromiseKit
*** Fetching OMGHTTPURLRQ
*** Checking out OMGHTTPURLRQ at "3.0.2"
*** Checking out PromiseKit at "3.0.0"
*** xcodebuild output can be found in /var/folders/lr/y1jtyy795b92s95ppqvk1xfh0000gn/T/carthage-xcodebuild.un4y1z.log
*** Building scheme "OMGiOS" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "PMKiOS" in PromiseKit.xcodeproj
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
warning: Capabilities that require entitlements from "Tests/Entitlements.plist" may not function in the Simulator because no development team was selected and no provisioning profiles matching an applicable signing identity were found. Select a development team in the target editor.
Code Sign error: No matching provisioning profiles found: No provisioning profiles matching an applicable signing identity were found.
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by aral** [comment] 2015-11-01 11:12
I get a similar fail:

	*** Cloning PromiseKit
	*** Cloning objective-git

	*** Cloning OMGHTTPURLRQ
	*** Checking out OMGHTTPURLRQ at "3.0.2"
	*** Downloading objective-git.framework binary at "0.8.8"
	*** Checking out PromiseKit at "3.0.0"
	*** xcodebuild output can be found in /var/folders/vp/l22f5841353_6v24wxvpxvw00000gn/T/carthage-xcodebuild.NCTnYp.log
	*** Building scheme "OMGOSX" in OMGHTTPURLRQ.xcodeproj
	*** Building scheme "OMGwatchOS" in OMGHTTPURLRQ.xcodeproj
	** BUILD FAILED **


	The following build commands failed:
		Check dependencies
	(1 failure)
	A shell task failed with exit code 65:
	** BUILD FAILED **


	The following build commands failed:
		Check dependencies
	(1 failure)

**Comment by aral** [comment] 2015-11-01 11:21
OK, oddly enough, when I reran carthage, it worked. I’d run it first time around with just `carthage update` and the second time with `carthage update --verbose --platform iOS` (to try and diagnose). This was with Carthage 0.9.3, btw. Just updated to the latest 0.9.4 but having tried an update with that yet.

Might be worth running update again as a workaround and seeing if it was some artefact in the first run that makes the second run succeed.

**Comment by aral** [comment] 2015-11-01 16:11
I can confirm that what fixed it wasn’t running it again but running it specifically for iOS `carthage update --platform iOS`. The OMGwatchOS target is what’s making it fail.

**Comment by diogoguimaraes** [comment] 2015-11-18 14:16
I'm not able to build PromiseKit 3.0 iOS scheme with Carthage too:
```Bash
*** Building scheme "PMKiOS" in PromiseKit.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
warning: Capabilities that require entitlements from "Tests/Entitlements.plist" may not function in the Simulator because no development team was selected and no provisioning profiles matching an applicable signing identity were found. Select a development team in the target editor.
Code Sign error: No matching provisioning profiles found: No provisioning profiles matching an applicable signing identity were found.
A shell task failed with exit code 65:
** BUILD FAILED **
```

I think it's due to the PMKiOSUITestsHost scheme having an iOS application target. Removing it fixes the carthage build.
Is it really necessary to have the iOS app target on the lib?

**Comment by diogoguimaraes** [comment] 2015-11-19 01:19
I've fixed the issue by unchecking the `Run` and `Archive` build options for the `PMKiOSUITests`target as seen below:

<img width="512" alt="screen shot 2015-11-19 at 01 08 52" src="https://cloud.githubusercontent.com/assets/8330387/11259521/26ed5918-8e5a-11e5-9763-a7ecab3ab0ba.png">

@mxcl is it possible to include this fix in a 3.0.1 tag?
Thank you.

**Comment by ypresto** [comment] 2015-12-14 09:53
Building with Carthage 0.11 fixed this issue (warnings are still printed).

**Comment by nathanhosselton** [comment] 2016-01-31 22:46
This should be resolved with the latest version of Carthage. Feel free to reopen if the issue persists.

**Closed by nathanhosselton** 2016-01-31 22:46 UTC

**Comment by opfeffer** [comment] 2016-07-27 12:57
I am seeing this issue resurface with PromiseKit 3.4.0 and Carthage 0.16.2

**Comment by mxcl** [comment] 2016-07-27 17:25
Fixed again.

**Comment by opfeffer** [comment] 2016-07-27 17:35
Thanks boss!
