### ISSUE TITLE
Undefined symbols for architecture arm64 : PromiseKit

### ISSUE THREAD

**Issue by mnive93** [mxcl/PromiseKit#1322] opened 2023-07-27 12:06 UTC
---

You read the guide but it didn’t help? OK, we’re here to help.

* PromiseKit 8.0.0

* We are building a third party library and  integrated PromiseKit via cocoapods within our library. We are getting the following error when we try to link the generated xcFramework within our app. Is there any way we can add PromiseKit within our library? Any help will be appreciated. "

`Undefined symbols for architecture arm64:
"PromiseKit.conf.getter : PromiseKit.PMKConfiguration", referenced from:
ld: symbol(s) not found for architecture arm64 `

**Comment by mxcl** [comment] 2023-07-27 13:32
it's likely a build configuration issue specific to yourselves since we've had no other such reports.

does cleaning and rebuilding help at all?

So little changed between v6 and v8 that I don't really see how it could be related to that.

**Comment by RomanPodymov** [comment] 2023-07-27 14:33
> You read the guide but it didn’t help? OK, we’re here to help.
> 
> * PromiseKit 8.0.0
> * We are building a third party library and  integrated PromiseKit via cocoapods within our library. We are getting the following error when we try to link the generated xcFramework within our app. Is there any way we can add PromiseKit within our library? Any help will be appreciated. "
> 
> `Undefined symbols for architecture arm64: "PromiseKit.conf.getter : PromiseKit.PMKConfiguration", referenced from: ld: symbol(s) not found for architecture arm64 `

Hello @mnive93 
And what about PromiseKit 6?

**Comment by RomanPodymov** [comment] 2024-05-11 08:21
Closing because we don't have enough context to reproduce this issue. You can reopen the issue with more details.

**Closed by RomanPodymov** 2024-05-11 08:21 UTC
Labels: bug, help wanted
