### ISSUE TITLE
Crash on iOS11/12

### ISSUE THREAD

**Issue by zzzzzyijie** [mxcl/PromiseKit#1295] opened 2022-08-27 14:39 UTC
it will crash on iOS11/12 
because of this code:

version: 6.18.0
#if swift(>=5.5)
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension Guarantee {
    func async() async -> T {
        await withCheckedContinuation { continuation in
            done { value in
                continuation.resume(returning: value)
            }
        }
    }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension Promise {
    func async() async throws -> T {
        try await withCheckedThrowingContinuation { continuation in
            done { value in
                continuation.resume(returning: value)
            }.catch { error in
                continuation.resume(throwing: error)
            }
        }
    }
}
#endif

**Comment by zzzzzyijie** [comment] 2022-08-27 14:58
verson: 6.18.1
Xcode: 13.2

it will crash too!! on iOS11/12...

#if swift(>=5.5)
#if canImport(_Concurrency)
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension Guarantee {
    func async() async -> T {
        await withCheckedContinuation { continuation in
            done { value in
                continuation.resume(returning: value)
            }
        }
    }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension Promise {
    func async() async throws -> T {
        try await withCheckedThrowingContinuation { continuation in
            done { value in
                continuation.resume(returning: value)
            }.catch { error in
                continuation.resume(throwing: error)
            }
        }
    }
}
#endif
#endif

**Comment by RomanPodymov** [comment] 2022-09-06 11:07
Hello @zzzzzyijie 
Please provide more details.

**Comment by isaac-weisberg** [comment] 2022-09-07 10:37
What does the crash say? Something generic like EXC_BAD_ACCESS or something more specific?

**Comment by RomanPodymov** [comment] 2024-05-11 08:12
Closing because I don't have enough context to reproduce this crash. Please create an example project with this crash and share it here once it is ready.

**Closed by RomanPodymov** 2024-05-11 08:12 UTC
