### ISSUE TITLE
join not working?

### ISSUE THREAD

**Issue by dtartaglia** [mxcl/PromiseKit#314] opened 2015-11-03 20:55 UTC
let promises: [Promise<Request>] = /* ... */
    let foo = join(promises)

I'm getting an error `Cannot invoke 'join' with argument list of type '([Promise<Request>])'`

I'm using `pod 'PromiseKit', '~> 3.0'`

Am I doing something wrong, or is `join` not working in Swift?

**Comment by mxcl** [comment] 2015-11-03 21:26
There is no version of join that takes an array, there is only a `Promise...` version, so you need to:

```swift
join(a, b, c)
```

This could be considered a Swift issue, but because we can't say if there will ever be a fix we need another version of join that takes an array. PR welcome.

**Comment by dtartaglia** [comment] 2015-11-03 22:49
hmm... I did the obvious thing:

    public func join<T>(promises: Promise<T>...) -> Promise<[T]> {
        return join(promises)
    }
    
    public func join<T>(promises: [Promise<T>]) -> Promise<[T]> {
    /*...*/

But I get a console message "PromiseKit: Pending Promise deallocated! This is usually a bug". I don't see that message when I use `when`... I don't understand the code well enough at this point...

**Comment by dtartaglia** [comment] 2015-11-03 23:00
I'm sending `join` a `[Promise<Int>]` and the console message is getting called on a `Promise<[Int]>`...

**Comment by mkhl** [comment] 2015-11-23 06:38
I needed something like `join` on an Array as well, so I wrote [an extension that implements `traverse` on `CollectionType`](https://gist.github.com/mkhl/40989cac8e33522d4fd2).
Maybe that helps?

**Comment by dtartaglia** [comment] 2015-11-23 11:54
It turns out that neither join nor when did what I needed anyway. I wrote a new function for myself... https://gist.github.com/dtartaglia/2b19e59beaf480535596

**Comment by nathanhosselton** [comment] 2015-11-30 16:55
Duplicate of https://github.com/mxcl/PromiseKit/issues/326

**Closed by nathanhosselton** 2015-11-30 16:55 UTC
