### ISSUE TITLE
swift-2.0.-beta5 branch unable to build with Carthage

### ISSUE THREAD

**Issue by appsmonkey** [mxcl/PromiseKit#288] opened 2015-10-08 07:55 UTC
### Carthage version
```
$ carthage version
0.8.0
```

### xcodebuild version
```
$ xcodebuild -version
Xcode 7.0
Build version 7A218
```

### Cartfile
```
github "mxcl/PromiseKit" "swift-2.0-beta5"
```
```
$ carthage update
*** Fetching PromiseKit
*** Fetching OMGHTTPURLRQ
*** Checking out PromiseKit at "c90cfc1c578ed09b5d3d21e0ac71aa5020be0899"
*** Checking out OMGHTTPURLRQ at "3.0.0"
*** xcodebuild output can be found in /var/folders/td/99svwd2x5b3g6nkwjv_3y52w0000gn/T/carthage-xcodebuild.SYp8un.log
*** Building scheme "OMGOSX" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "OMGiOS" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "PMKOSX" in PromiseKit.xcodeproj
*** Building scheme "PMKwatchOS" in PromiseKit.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

### Log file
```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET PMKwatchOS OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies
target 'PMKwatchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
```

**Comment by nathanhosselton** [comment] 2015-10-08 16:14
duplicate of #285

**Closed by nathanhosselton** 2015-10-08 16:14 UTC
